name: Release
run-name: Release ${{ github.ref_name}}

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: get version
        id: version
        run: echo "result=$(jq -r .version < package.json)" >> $GITHUB_OUTPUT

      - run: npm ci
      - run: npm run package:vsix

      - uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: settings-sync-${{ steps.version.outputs.result }}.vsix
